.TH "DAHDI_TOOL" "8" "16 June 2008" "" ""

.SH NAME
dahdi_tool \- Shows status of DAHDI interfaces
.SH SYNOPSIS

.B dahdi_tool

.SH DESCRIPTION
dahdi_tool shows the current status the DAHDI inteface cards plugged 
to the computer.

It displays values like Current Alarms, SyncSource, Tx/Rx
Levels for each DAHDI interface.

.SH SEE ALSO
dahdi_monitor(8), asterisk (8).

.SH AUTHOR
This manual page was written by Santiago Ruano Rinc\['o]n 
<santiago@unicauca.edu.co> for
the Debian system (but may be used by others).  Permission is
granted to copy, distribute and/or modify this document under
the terms of the GNU General Public License, Version 2 any 
later version published by the Free Software Foundation.
