.TH "ASTRIBANK_TOOL" "8" "29 March 2009" "" ""

.SH NAME
astribank_tool \- Xorcom Astribank (xpp) control tool
.SH SYNOPSIS
.B astribank_tool [ options ] [ operation... ] \-D \fIdevice-path\fR

.B astribank_tool [\-h]

.SH DESCRIPTION
.B astribank_tool
is a tool to control the USB-level functionality of an Astribank.
The tool operates on a single Astribank at a time (given as parameter
to the \-D command line option).

.SH OPTIONS
.B \-D 
.I device-path
.RS
Required. The device to read from/write to. This is
\fIbus_num\fR/\fIdevice_num\fR, where \fIbus_num\fR and \fIdevice_num\fR
are the first two numbers in the output of lsusb(8) or dahdi_hardware(8).
On older versions of this tool you needed a complete path to the device,
which would be /dev/bus/usb/\fIbus_num\fR/\fIdevice_num\fR, or
/proc/bus/usb/\fIbus_num\fR/\fIdevice_num\fR.
.RE

.B \-p \fInum\fR
.RS
Set the TwinStar port number. Either 0 or 1.

(TODO: explain).
.RE

.B \-r \fItype\fR
.RS
Reset the Astribank and renumerate its USB connection to power on product ID.

Tyep can be: \fBhalf\fR or \fBfull\fR.

(TODO: explain those).
.RE

.B \-w 0|1
.RS
Enable (1) or disable (0) the TwinStar watchdog. When enabled, the
Astribank will jump to the second port if this system is "not working"
and the system on the second port is available.
.RE

.B \-Q
.RS
Query astribank properties via MPP protocol.
.RE

.B \-n
.RS
Renumerate the Astribank product number (e.g: from 1161 to 1162).
.RE

.B \-v
.RS
Increase verbosity. May be used multiple times.
.RE

.B \-d \fImask\fR
.RS
Set debug mask to \fImask\fR. Default is 0, 0xFF is "everything".
.RE

.B \-h
.RS
Displays usage message.
.RE

.SH SEE ALSO
fxload(8), lsusb(8), astribank_hexload(8)

.SH AUTHOR
This manual page was written by Tzafrir Cohen <tzafrir.cohen@xorcom.com> .
Permission is granted to copy, distribute and/or modify this document under
the terms of the GNU General Public License, Version 2 any 
later version published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public
License can be found in /usr/share/common\-licenses/GPL.
