obj-$(DAHDI_BUILD_ALL)$(CONFIG_DAHDI_WCTC4XXP) += wctc4xxp.o

FIRM_DIR	:= ../firmware

ccflags-y += -I$(src)/.. -Wno-undef

ifeq ($(HOTPLUG_FIRMWARE),yes)
  ccflags-y+=-DHOTPLUG_FIRMWARE
endif

wctc4xxp-objs := base.o

ifneq ($(HOTPLUG_FIRMWARE),yes)
wctc4xxp-objs += $(FIRM_DIR)/dahdi-fw-tc400m.o
endif

$(obj)/$(FIRM_DIR)/dahdi-fw-tc400m.o: $(obj)/base.o
	$(MAKE) -C $(obj)/$(FIRM_DIR) dahdi-fw-tc400m.o
