name: DAHDI Kernel CI for LTS kernels

on:
  schedule:
    - cron: 00 02 * * *
  pull_request:

jobs:
  kernel_test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        kernel_branch: [
          'linux-4.14.y',
          'linux-4.19.y',
          'linux-5.4.y',
          'linux-5.10.y',
          'linux-5.15.y',
          'linux-6.1.y'
          ]
    steps:
      call-kernel-check:
        uses: asterisk/dahd-linux/.github/workflows/kernel-check.yaml@v1
        with:
          kernel-git-cache: kernel-git-cache
          kernel-git-repo: git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
          kernel-git-branch: ${{ matrix.kernel_branch }}
